using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Fireball : MonoBehaviour
{
    [SerializeField] private GameObject fiiiiiire;

    public float speed = 10.0f;
    public int damage = 1;

    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {
        transform.Translate(0, 0, speed * Time.deltaTime);
    }

    void OnTriggerEnter(Collider other) //Эта функция вызывается, когда с триггером сталкивается другой объект.
    {
        PlayerCharacter player = other.GetComponent<PlayerCharacter>();
        if (player != null) //Проверяем, является ли этот другой объект объектом PlayerCharacter.
        {
            Debug.Log("Player hit");
            player.Hurt(damage);
            Destroy(this.gameObject);
        }
        Destroy(this.gameObject);
    }
}
